//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class viziteEntities : DbContext
    {
        public viziteEntities()
            : base("name=viziteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doktortablo> doktortabloes { get; set; }
        public virtual DbSet<kayitliamirtablo> kayitliamirtabloes { get; set; }
        public virtual DbSet<scanner> scanners { get; set; }
        public virtual DbSet<temelcalisantablo> temelcalisantabloes { get; set; }
        public virtual DbSet<vizitealanlartablo> vizitealanlartabloes { get; set; }
        public virtual DbSet<departmanlar> departmanlars { get; set; }
    }
}
