//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vizitealanlartablo
    {
        public int id { get; set; }
        public string sicilno { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public Nullable<System.DateTime> sevk_tarihi { get; set; }
        public Nullable<System.DateTime> sevk_saati { get; set; }
        public Nullable<int> yakakodu { get; set; }
        public Nullable<int> durum { get; set; }
    }
}
